# Datawrapper configuration
#

domain: datawrapper.de
chart_domain: c.datawrapper.de

# show debug message?
debug: true

# some default values
default_theme: default
default_vis: bar-chart

# thumbnail sizes [width, height]
thumbnails:
    s: [150, 150]
    m: [260, 170]

# email address for admin
admin_email: hello@datawrapper.de
log_email: debug@datawrapper.de

# piwik tracking code
piwik:
    url: datastory.de/piwik  # without http:// and trailing slash
    idSite: 5
    # idSiteNoCharts: 6  # additionally, you can track the user interface w/o the charts, too